name: Deploy to Hostinger via FTP

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build project
        run: npm ci && npm run build

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v3.1.2
        with:
          ftp-server: ${{ secrets.HOSTINGER_FTP_HOST }}
          ftp-username: ${{ secrets.HOSTINGER_FTP_USER }}
          ftp-password: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
          port: ${{ secrets.HOSTINGER_FTP_PORT }}
          local-dir: dist
          server-dir: /domains/zybailo.com/public_html
