name: Deploy to Hostinger

on:
  push:
    branches:
      - main   # или prod, если используешь ветку deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v3.1.2
        with:
          ftp-server: ${{ secrets.HOSTINGER_FTP_HOST }}
          ftp-username: ${{ secrets.HOSTINGER_FTP_USER }}
          ftp-password: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
          local-dir: dist
          server-dir: /domains/zybailo.com/public_html
          method: sftp
          source: "dist/*"
          target: "/domains/zybailo.com/public_html"
          strip_components: 0
          timeout: 30s
          command_timeout: 10m
          overwrite: true
